apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence
  namespace: confluence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      serviceAccountName: confluence-monitoring-sa
      automountServiceAccountToken: true
      containers:
        - name: confluence
          image: atlassian/confluence-server:8.5.0
          ports:
            - containerPort: 8090
          env:
            - name: ATL_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/confluence"
            - name: ATL_JDBC_USER
              value: "confluence"
            - name: ATL_DB_TYPE
              value: postgresql
            - name: ATL_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/atlassian/application-data/confluence
              name: confluence-data
      volumes:
        - name: confluence-data
          persistentVolumeClaim:
            claimName: confluence-pvc
