apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-role-binding
  namespace: confluence
subjects:
- kind: ServiceAccount
  name: confluence-monitoring-sa
  namespace: confluence
roleRef:
  kind: Role
  name: monitoring-role
  apiGroup: rbac.authorization.k8s.io
