apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: gitlab-runner
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
