apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: gitlab-runner
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQUVYQU1QTEVLRVk= #AKIAEXAMPLEKEY - test keys non functional
  AWS_SECRET_ACCESS_KEY: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ== #wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY - test keys non functional
